### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by AlexBodner** [Dere-Wah/AI-MarioKart64#1]
In the README you say that to train the model we must run src/training.py, but there is no such file. Did you mean something like python3 src/main.py ?

**Comment by AlexBodner** [comment]
BTW, when running like I said, I get error:
alex@Alex:/mnt/c/Users/alex_/Documents/Udesa/3ero/Vision/TP Final Vision/AI-MarioKart64/diamond$ python3 src/main.py  common.devices=0
--- DENOISER ---
DENOISER Grad acc steps: 6
DENOISER batch size: 2
--- UPSAMPLER ---
UPSAMPLER Grad acc steps: 2
UPSAMPLER batch size: 2
path_data_low_res: [default: processed/low_res]
processed/low_res
path_data_full_res: [default: processed/full_res]
processed/full_res
Starting on cuda:0
/home/alex/.local/lib/python3.10/site-packages/torch/utils/data/sampler.py:76: UserWarning: `data_source` argument is not used and will be removed in 2.2.0.You may still have custom implementation that utilizes it.
  warnings.warn(
330466691 parameters in denoiser
51149187 parameters in upsampler
train_dataset: 0 episodes, 0 steps.
test_dataset: 0 episodes, 0 steps.

Epoch 1 / 1500

Error executing job with overrides: ['common.devices=0']
Traceback (most recent call last):
  File "/mnt/c/Users/alex_/Documents/Udesa/3ero/Vision/TP Final Vision/AI-MarioKart64/diamond/src/main.py", line 43, in main
    run(cfg, root_dir)
  File "/mnt/c/Users/alex_/Documents/Udesa/3ero/Vision/TP Final Vision/AI-MarioKart64/diamond/src/utils.py", line 304, in inner
    func(*args, **kwargs)
  File "/mnt/c/Users/alex_/Documents/Udesa/3ero/Vision/TP Final Vision/AI-MarioKart64/diamond/src/main.py", line 57, in run
    trainer.run()
  File "/mnt/c/Users/alex_/Documents/Udesa/3ero/Vision/TP Final Vision/AI-MarioKart64/diamond/src/trainer.py", line 271, in run
    to_log += self.train_agent()
  File "/mnt/c/Users/alex_/Documents/Udesa/3ero/Vision/TP Final Vision/AI-MarioKart64/diamond/src/trainer.py", line 364, in train_agent
    to_log += self.train_component(name, steps)
  File "/mnt/c/Users/alex_/Documents/Udesa/3ero/Vision/TP Final Vision/AI-MarioKart64/diamond/src/trainer.py", line 388, in train_component
    data_iterator = iter(data_loader) if data_loader is not None else None
  File "/home/alex/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 479, in __iter__
    self._iterator = self._get_iterator()
  File "/home/alex/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 415, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/alex/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1191, in __init__
    self._reset(loader, first_iter=True)
  File "/home/alex/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1228, in _reset
    self._try_put_index()
  File "/home/alex/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1471, in _try_put_index
    index = self._next_index()
  File "/home/alex/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 691, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/mnt/c/Users/alex_/Documents/Udesa/3ero/Vision/TP Final Vision/AI-MarioKart64/diamond/src/data/batch_sampler.py", line 36, in __iter__
    yield self.sample()
  File "/mnt/c/Users/alex_/Documents/Udesa/3ero/Vision/TP Final Vision/AI-MarioKart64/diamond/src/data/batch_sampler.py", line 56, in sample
    episode_ids = np.random.choice(episodes_partition, size=max_eps, replace=True, p=weights / weights.sum())
  File "numpy/random/mtrand.pyx", line 950, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by Dere-Wah** [comment]
Hello Alex, thank you for the issue.

First of all, yes, to start the training run you must run `src/main.py` and not `src/training.py`

ReadMe docs are still a big WIP as there are a bunch of scope changes I'm going through, so be on the look out for more issues like that 😅 To be 100% sure feel free to compare the process or the files with the original diamond repo, which is a complete and published research and therefore is not undergoing changes likes this one. https://github.com/eloialonso/diamond/tree/csgo

Regarding your second issue, the file path you specified for the training is wrong. The script has no clue where your processed dataset is:

```
train_dataset: 0 episodes, 0 steps.
test_dataset: 0 episodes, 0 steps.
```

To ensure this is set, when running the script (or in the config) put ABSOLUTE file paths instead of relative ones. 
Your config paths are set to:
processed/low_res
processed/full_res

While they actually should be:
/mnt/c/Users/alex_/Documents/Udesa/3ero/Vision/TP Final Vision/AI-MarioKart64/diamond/processed/low_res
/mnt/c/Users/alex_/Documents/Udesa/3ero/Vision/TP Final Vision/AI-MarioKart64/diamond/processed/full_res
(deducing from your issue log)

Hope this helps!

**Comment by AlexBodner** [comment]
Thank you a lot!
